Review
bl0rch1d/library pull request #1
Opened 2019-05-10 09:10 UTC by bl0rch1d

2019-05-13 07:47 UTC, yuriy1991 commented on .ruby-version
> +ext-ruby-2.5.5
Why not just `2.5.5`?

2019-05-13 08:01 UTC, yuriy1991 commented on entities/author.rb
> +    @name = name
Let's add validation. It should be a String and it shouldn't be empty
Please add validations to other entities as well

2019-05-13 08:03 UTC, yuriy1991 commented on entities/library.rb
> +require 'yaml'
Let's load requires to `autoload.rb` and then require autoload in `main.rb`

2019-05-13 08:10 UTC, yuriy1991 commented on entities/library.rb
> +    raise ArgumentError unless Config::ENTITIES.include? name.to_sym
Let's use a `case` here:
```
def add_entity(entity)
   case entity
     when Author then @authors << entity
     ...
```

2019-05-13 08:12 UTC, yuriy1991 commented on entities/library.rb
> +  def statistics
Let's move statistics related methods to `Statistics` module

2019-05-13 08:12 UTC, yuriy1991 commented on entities/library.rb
> +  def save_data
Let's move persistence related methods to `Storage/Database` module

2019-05-13 08:14 UTC, yuriy1991 commented on entities/reader.rb
> +  def initialize(name, email, city, street, house)
I think keyword arguments would be more readable

2019-05-13 08:15 UTC, yuriy1991 commented on main.rb
> +lib.add_entity Author.new('name', 'bio'), :author
let's use `ffaker/faker` gem  for data generation

2019-05-13 08:20 UTC, yuriy1991 commented on utils/statistics.rb
> +  def get_top_reader
it should accept an argument (default 1)

2019-05-13 08:20 UTC, yuriy1991 commented on utils/statistics.rb
> +  def get_top_books
it should accept an argument (default 1)

2019-05-13 08:21 UTC, yuriy1991 commented on utils/statistics.rb
> +  def get_readers_of_popular_books
it should accept an argument (default 3)

2019-05-13 08:23 UTC, yaorlov requested changes
Please run rubocop and fix issues

2019-05-13 08:44 UTC, yuriy1991 commented on utils/statistics.rb
> +    res = @orders
Let's use more descriptive naming

2019-05-13 08:45 UTC, yuriy1991 commented on utils/statistics.rb
> +          .max_by(num) { |_, x| x.size }
`.max_by(num) { |_entity, orders| orders.size }`

2019-05-13 08:54 UTC, yuriy1991 commented
Please add 1 file with stored data (.yml, .json, e.t.c) that is used for data uploading (instead of multiple `#{entity}s.yaml`).
The files that are generated after `save_data` calls should be under gitignore

2019-05-13 09:10 UTC, bl0rch1d commented on entities/library.rb
> +    raise ArgumentError unless Config::ENTITIES.include? name.to_sym
А почему case предпочтительней? Из-за читаемости?

2019-05-13 11:01 UTC, yuriy1991 commented on entities/library.rb
> +    raise ArgumentError unless Config::ENTITIES.include? name.to_sym
из-за читаемости + аргументов меньше

2019-05-13 11:14 UTC, bl0rch1d commented on entities/library.rb
> +    raise ArgumentError unless Config::ENTITIES.include? name.to_sym
понял, спасибо

2019-05-16 05:42 UTC, yuriy1991 commented on config.rb
> +  ENTITIES = %i[author book reader order].freeze
this constant is used only in `db.rb`, please move it to that file

2019-05-16 05:49 UTC, yuriy1991 commented on entities/author.rb
> +  attr_accessor :name, :bio
`attr_reader :name, :bio`?

2019-05-16 05:51 UTC, yuriy1991 commented on entities/author.rb
> +    @name
if you have `attr_reader`/`attr_accessor` you can omit `@`

2019-05-16 05:51 UTC, yuriy1991 commented on entities/book.rb
> +  attr_accessor :title, :author
`attr_reader`?

2019-05-16 05:51 UTC, yuriy1991 commented on entities/book.rb
> +    "#{@title}, #{@author}"
"#{title}, #{author}"

2019-05-16 05:52 UTC, yuriy1991 commented on entities/book.rb
> +    title.instance_of?(String) && !title.empty? && author.instance_of?(Author)
validation logic is repeated in all entities, let's extract validation methods to `Validate` module

2019-05-16 05:53 UTC, yuriy1991 commented on entities/library.rb
> +# Creates object which represents Library
please remove explanation comments, the ruby code should be self-explanatory)

2019-05-16 05:54 UTC, yuriy1991 commented on entities/library.rb
> +  def initialize(authors = [], books = [], readers = [], orders = [])
Let's use keyword arguments for better readability:
`def initialize(authors: [], books: [], readers: [], orders: [])`

2019-05-16 05:55 UTC, yuriy1991 commented on entities/library.rb
> +  attr_accessor :authors, :readers, :books, :orders
do we really need `attr_accessor`?

2019-05-16 05:58 UTC, yuriy1991 commented on entities/library.rb
> +    data :save
`add_entity` method should have 1 responsibility, please remove saving data from here

2019-05-16 05:59 UTC, yuriy1991 commented on entities/library.rb
> +  def data(action)
this helper method shouldn't be in the library class

2019-05-16 05:59 UTC, yuriy1991 commented on entities/order.rb
> +  attr_accessor :book, :reader, :date
same comment as for other entities

2019-05-16 06:00 UTC, yuriy1991 commented on entities/library.rb
> +    send :"#{action}_data"
better use `public_send`

2019-05-16 06:11 UTC, yuriy1991 commented on utils/db.rb
> +    Config::ENTITIES.each do |entity|
Code with metaprogramming looks shorter, but it's less readable. I would better do smth like this:
```
data = FakeDataGenerator.call # returns a hash {authors: [], books: [], orders: [], readers: []}
authors  = data[:authors]
books    = data[:books]
orders   = data[:orders]
readers  = data[:readers]
```
Also you could extract common code (`authors  = data[:authors]`...) from `load_data` and `generate data` to a separate method.
You don't have to change this, just my thoughts

2019-05-16 06:28 UTC, yuriy1991 commented on utils/statistics.rb
> +    res = @orders
let's name it `result`

2019-05-16 07:13 UTC, bl0rch1d commented on entities/library.rb
> +# Creates object which represents Library
Я их вписал, потому что линтер ругается на то, что нет top class documentation comment

2019-05-16 07:45 UTC, bl0rch1d commented on entities/library.rb
> +# Creates object which represents Library
мне все комментарии убрать?

2019-05-16 08:11 UTC, yuriy1991 commented on entities/library.rb
> +# Creates object which represents Library
для классов можешь оставить (чтоб рубокоп не ругался), убери для методов
а на будущее можешь отключать это правило рубокопа и не писать комментарии на классами

2019-05-16 08:13 UTC, bl0rch1d commented on entities/library.rb
> +    send :"#{action}_data"
load_data приватный метод и я не могу использовать public_send

2019-05-16 09:11 UTC, yuriy1991 commented on utils/db.rb
> +    parse data
we are not parsing data here. let's call it `add_to_library` or smth like this

2019-05-16 09:12 UTC, yaorlov commented on utils/fake_data_generator.rb
> +      @authors = Array.new(rand(5..LIMIT)) do
we don't need to assign array to the instance variable

2019-05-16 09:16 UTC, yuriy1991 commented on utils/db.rb
> +  def data(action)
I don't really like using `send` and raising an exception:
```
unless private_methods.include? :"#{action}_data"
  raise ArgumentError, 'Invalid action'
end
```
Let's remove `data` method and make other methods public (will be used like `library.save_data`)

2019-05-16 09:19 UTC, bl0rch1d commented on utils/fake_data_generator.rb
> +      @authors = Array.new(rand(5..LIMIT)) do
там дальше есть места, где эти переменные нужны
![image](https://user-images.githubusercontent.com/38437488/57842240-ca297f00-77d4-11e9-8a85-3f3d8e6f19f6.png)

2019-05-16 09:24 UTC, yuriy1991 commented on utils/validate.rb
> +  def valid?(*props)
this module should contain helper methods like this:
```
def check_class(instance, klass)
  raise WrongClassError unless instance.instance_of? klass
end
```
Also, let's create `errors.rb` file that will contain error classed for our validations.
```
module Errors
  class WrongClassError < StandardError
    def initialize
      super('Error message')
    end
  end
end
```

2019-05-16 09:25 UTC, yuriy1991 commented on utils/fake_data_generator.rb
> +      @authors = Array.new(rand(5..LIMIT)) do
ok

2019-05-16 11:20 UTC, yaorlov approved these changes

2019-05-16 11:26 UTC, merged